local_costmap:
  global_frame: /map
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 1.0
  static_map: true 
  rolling_window: true
  width: 5.0
  height: 4.0
  resolution: 0.05
  plugins:
   - {name: footprint_layer, type: "costmap_2d::FootprintLayer"}
