local_costmap:
  plugins:
   - {name: static_layer, type: "costmap_2d::StaticLayer2"}
   - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
   - {name: voxel_layer, type: "costmap_2d::VoxelLayer"}
   - {name: footprint_layer, type: "costmap_2d::FootprintLayer"}
   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  voxel_layer:
    observation_sources: points_c points_m 
#    observation_sources: points
    combination_method: 1
    publish_voxel_map: true
    z_resolution: 0.1
    z_voxels: 14
    origin_z: 0.1
#    points: {topic: /camera2/depth/points, data_type: PointCloud2, expected_update_rate: 1.5, observation_persistence: 0.0, marking: true, clearing: true, min_obstacle_height: -1.0, max_obstacle_height: 5.0}
    points_c: {topic: /camera2/depth/points, data_type: PointCloud2, expected_update_rate: 1.5, observation_persistence: 0.0, marking: false, clearing: true, min_obstacle_height: -0.5, max_obstacle_height: 5.0, raytrace_range: 6.0, inf_is_valid: true}
    points_m: {topic: /camera2/depth/points, data_type: PointCloud2, expected_update_rate: 1.5, observation_persistence: 0.0, marking: true, clearing: false, min_obstacle_height: 0.15, max_obstacle_height: 1.2, inf_is_valid: true}
