#http://wiki.ros.org/move_base?distro=hydro

base_global_planner: "navfn/NavfnROS"
base_local_planner: "grid_local_planner/GridPlannerROS"

planner_frequency: 0
shutdown_costmaps: true

controller_frequency: 0.8
